Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).



In [16]:
import numpy as np

N = int(input('Введите N: '))

print(np.arange((N-1), -1, -1))
np.arange((N-1), -1, -1)

Введите N: 10
[9 8 7 6 5 4 3 2 1 0]


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.



In [25]:
import numpy as np

N = int(input('Введите N: '))

m = np.diag(np.arange((N-1), -1, -1))
print('')
print('Матрица: ')
print('')
print(m)
print('')

count = 0
for line in m:
    count += sum(line)

print('Сумма элементов по диагонали: ', count)

Введите N: 10

Матрица: 

[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]

Сумма элементов по диагонали:  45


Задание 3
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3



In [30]:
import numpy as np

a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])

result = np.linalg.solve(a, b)

print(result)

s_1 = 0.46666667 * 4 + 2 * 3.84444444 - 1 * 5.55555556
s_2 = 0.46666667 * 1 + 3 * 3.84444444 - 0 * 5.55555556
s_3 = 0.46666667 * 0 + 5 * 3.84444444 - 4 * 5.55555556

print(s_1, s_2, s_3)

[ 0.46666667  3.84444444 -5.55555556]
4.0 11.999999990000001 -3.0000000399999998


Задание 4
В материалах занятия раздел “Задача 4 домашнего задания”

Найдите самого похожего пользователя. Т. е. посчитайте косинусное расстояние между этим пользователем и всеми пользователями из массива user_stats


In [58]:
import numpy as np


# Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. 
# Остальные столбцы - количество покупок категорий товаров этим пользователем:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)


# На сайт заходит очередной посетитель, о покупках которого известно следующее:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])


def cosine( a, b ):
    
    # Подсчет косинуса угла между векторами a, b по их координатам
    
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

i = 0
users_cosine_dict = {}
users_cosine_list = []
for a in users_stats:
    i += 1
    c = cosine( a, next_user_stats )
    users_cosine[i] = c
    users_cosine_list.append(c)
    print(f'id = {i}:', f'Косинусное расстояние: {c};')

for ids, cosines  in users_cosine.items():
    if cosines == max(users_cosine_list):
        print('')
        print(f'Id самого похожего пользователя: {ids};', f'Косинусное расстояние: {cosines};')

id = 1: Косинусное расстояние: 0.19999999999999996;
id = 2: Косинусное расстояние: 0.8451542547285165;
id = 3: Косинусное расстояние: 0.3999999999999999;
id = 4: Косинусное расстояние: 0.7905694150420948;
id = 5: Косинусное расстояние: 0.3999999999999999;
id = 6: Косинусное расстояние: 0.0;
id = 7: Косинусное расстояние: 0.0;
id = 8: Косинусное расстояние: 0.9486832980505138;
id = 9: Косинусное расстояние: 0.0;
id = 10: Косинусное расстояние: 0.0;

Id самого похожего пользователя: 8; Косинусное расстояние: 0.9486832980505138;
